import io, csv, json, os, base64
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from sqlalchemy.orm import Session as DBSession

from ..database import get_db
from ..config import settings
from ..models import ExportLog, SourceFile
from ..dependencies import get_principal
from ..permissions import Principal
from ..services import audit, visible_curriculum_items

router = APIRouter(prefix="/api", tags=["export-import"])


# "program-items" is kept as an alias so existing links and bookmarks do not
# start returning 400. It serves curriculum items now: ProgramItem was retired
# when CurriculumItem became the canonical entity (Part 41), and this was the
# only export type the CSV/XLSX/PDF endpoints supported -- deleting it outright
# would have left all three unable to export anything at all.
_CURRICULUM_EXPORT_TYPES = ("curriculum-items", "program-items")


def _rows_for(export_type: str, db: DBSession, p: Principal) -> tuple[list[str], list[list]]:
    if export_type in _CURRICULUM_EXPORT_TYPES:
        items = visible_curriculum_items(db, p)
        headers = ["identifier", "code", "title", "owning_level", "phase", "element",
                   "core_status", "duration_minutes", "recommended_term", "learning_hub_linked"]
        rows = [[it.identifier or "", it.code, it.title, it.owning_level, it.phase,
                 it.element or "", it.core_status, it.duration_minutes,
                 it.recommended_term or "", "yes" if it.learning_hub_url else "no"]
                for it in items]
        return headers, rows
    raise HTTPException(400, detail={"error": "unsupported_export_type"})


def _neutralise(v):
    s = str(v)
    return ("'" + s) if s[:1] in ("=", "+", "-", "@") else s


@router.get("/export/{export_type}.csv")
def export_csv(export_type: str, db: DBSession = Depends(get_db), p: Principal = Depends(get_principal)):
    headers, rows = _rows_for(export_type, db, p)
    buf = io.StringIO(); w = csv.writer(buf); w.writerow(headers)
    for r in rows:
        w.writerow([_neutralise(c) for c in r])
    _log(db, p, export_type, "csv", len(rows))
    buf.seek(0)
    return StreamingResponse(iter([buf.getvalue()]), media_type="text/csv",
                             headers={"Content-Disposition": f"attachment; filename={export_type}.csv"})


@router.get("/export/{export_type}.xlsx")
def export_xlsx(export_type: str, db: DBSession = Depends(get_db), p: Principal = Depends(get_principal)):
    import openpyxl
    headers, rows = _rows_for(export_type, db, p)
    wb = openpyxl.Workbook(); ws = wb.active; ws.title = export_type[:31]
    ws.append(headers)
    for r in rows:
        ws.append([_neutralise(c) for c in r])  # neutralise formulas on export
    bio = io.BytesIO(); wb.save(bio); bio.seek(0)
    _log(db, p, export_type, "xlsx", len(rows))
    return StreamingResponse(bio, media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                             headers={"Content-Disposition": f"attachment; filename={export_type}.xlsx"})


@router.get("/export/{export_type}.pdf")
def export_pdf(export_type: str, db: DBSession = Depends(get_db), p: Principal = Depends(get_principal)):
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
    from reportlab.lib.styles import getSampleStyleSheet
    from datetime import datetime, timezone
    headers, rows = _rows_for(export_type, db, p)
    bio = io.BytesIO()
    doc = SimpleDocTemplate(bio, pagesize=A4, title="AAFC TMS")
    styles = getSampleStyleSheet()
    story = [Paragraph("AAFC Training Management System", styles["Title"]),
             Paragraph(f"Report: {export_type}", styles["Heading2"]),
             Paragraph(f"Generated by role {p.role} at {datetime.now(timezone.utc).isoformat()}Z", styles["Normal"]),
             Spacer(1, 12)]
    data = [headers] + rows[:500]
    t = Table(data, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#002F65")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 7),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#D8DEE4")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F5F7FA")]),
    ]))
    story += [t, Spacer(1, 12), Paragraph("This system supports planning; it does not replace CEA/CadetNet.", styles["Italic"])]
    doc.build(story)
    bio.seek(0)
    _log(db, p, export_type, "pdf", len(rows))
    return StreamingResponse(bio, media_type="application/pdf",
                             headers={"Content-Disposition": f"attachment; filename={export_type}.pdf"})


def _log(db, p, export_type, fmt, n):
    db.add(ExportLog(user_id=p.user_id, scope=("national" if p.is_national else "wing" if p.is_wing else "squadron"),
                     export_type=f"{export_type}.{fmt}", filename=f"{export_type}.{fmt}", row_count=n))
    db.commit()
    audit(db, p, object_type="export", object_id=None, action="export", new={"type": export_type, "fmt": fmt, "rows": n})


# ── Program source import (reads real .xlsx/.xlsm) ──
class ProgramImportPreviewIn(BaseModel):
    source_category: str = "703_schedule"
    filename: str = "upload.xlsx"
    # base64 of the workbook bytes (frontend uploads; here also used by tests)
    file_b64: str


@router.post("/program-imports/preview")
def program_import_preview(body: ProgramImportPreviewIn, db: DBSession = Depends(get_db),
                           p: Principal = Depends(get_principal)):
    """Inspect a real workbook: list sheets and detect likely program columns.

    Does not commit anything. Treats all cell content as data (no formula execution).
    """
    if p.role not in ("sqn_admin", "wing_admin", "national_admin", "system_admin"):
        raise HTTPException(403, detail={"error": "forbidden"})
    try:
        raw = base64.b64decode(body.file_b64)
    except Exception:
        raise HTTPException(400, detail={"error": "bad_base64"})
    if len(raw) > settings.UPLOAD_MAX_MB * 1024 * 1024:
        raise HTTPException(413, detail={"error": "file_too_large"})
    import openpyxl
    try:
        wb = openpyxl.load_workbook(io.BytesIO(raw), read_only=True, data_only=True)
    except Exception as e:
        raise HTTPException(400, detail={"error": "unreadable_workbook", "message": str(e)[:120]})
    sheets = []
    program_keywords = ["code", "title", "module", "phase", "duration", "learning hub", "url",
                        "facilitator", "room", "element", "date", "period", "mission"]
    for ws in wb.worksheets[:30]:
        headers = []
        for row in ws.iter_rows(min_row=1, max_row=1, values_only=True):
            headers = [str(c).strip() if c is not None else "" for c in row][:40]
            break
        likely = [h for h in headers if any(k in h.lower() for k in program_keywords)]
        sheets.append({"sheet": ws.title, "headers": headers, "likely_program_columns": likely,
                       "looks_like_program": len(likely) >= 2})
    sf = SourceFile(filename=body.filename, file_type="xlsx", source_category=body.source_category,
                    uploaded_by=p.user_id, parsed_status="parsed", row_count=0)
    db.add(sf); db.commit()
    audit(db, p, object_type="source_file", object_id=sf.id, action="import",
          new={"category": body.source_category, "sheets": len(sheets)})
    return {"source_file_id": sf.id, "sheet_count": len(sheets), "sheets": sheets,
            "note": "Preview only. Column mapping + commit to draft package is the next step (see CADET_PROGRAM_INTEGRATION.md)."}
