"""create_custom_training_phases
Revision ID: 0ae75ee5aed6
Revises: 8dfa66dab8b6
Create Date: 2026-08-21 20:23:00.027485
"""
from alembic import op
import sqlalchemy as sa

revision = '0ae75ee5aed6'
down_revision = '8dfa66dab8b6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_training_phases',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=True),
    sa.Column('applies_from', sa.String(length=10), nullable=False),
    sa.Column('applies_to', sa.String(length=10), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_training_phases_scope_id'), 'custom_training_phases', ['scope_id'], unique=False)
    op.create_index(op.f('ix_custom_training_phases_scope_type'), 'custom_training_phases', ['scope_type'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_training_phases_scope_type'), table_name='custom_training_phases')
    op.drop_index(op.f('ix_custom_training_phases_scope_id'), table_name='custom_training_phases')
    op.drop_table('custom_training_phases')
    # ### end Alembic commands ###
