"""v9.1 cadet program + jobs
Revision ID: 175e1c6e12f7
Revises: 
Create Date: 2026-06-20 00:15:29.092163
"""
from alembic import op
import sqlalchemy as sa

revision = '175e1c6e12f7'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_items',
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('squadron_id', sa.String(length=36), nullable=True),
    sa.Column('wing_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('due_date', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('linked_object_type', sa.String(length=40), nullable=True),
    sa.Column('linked_object_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('closed_by', sa.String(length=36), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closure_note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_items_squadron_id'), 'action_items', ['squadron_id'], unique=False)
    op.create_index(op.f('ix_action_items_status'), 'action_items', ['status'], unique=False)
    op.create_index(op.f('ix_action_items_wing_id'), 'action_items', ['wing_id'], unique=False)
    op.create_table('activities',
    sa.Column('owning_level', sa.String(length=20), nullable=False),
    sa.Column('national_id', sa.String(length=36), nullable=True),
    sa.Column('wing_id', sa.String(length=36), nullable=True),
    sa.Column('squadron_id', sa.String(length=36), nullable=True),
    sa.Column('activity_name', sa.String(length=200), nullable=False),
    sa.Column('activity_type', sa.String(length=40), nullable=True),
    sa.Column('date_start', sa.String(length=10), nullable=False),
    sa.Column('date_end', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('oic', sa.String(length=120), nullable=True),
    sa.Column('twoic', sa.String(length=120), nullable=True),
    sa.Column('risk_status', sa.String(length=20), nullable=False),
    sa.Column('permission_status', sa.String(length=20), nullable=False),
    sa.Column('workflow_status', sa.String(length=30), nullable=False),
    sa.Column('closeout_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_is_archived'), 'activities', ['is_archived'], unique=False)
    op.create_index(op.f('ix_activities_squadron_id'), 'activities', ['squadron_id'], unique=False)
    op.create_index(op.f('ix_activities_wing_id'), 'activities', ['wing_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('wing_id', sa.String(length=36), nullable=True),
    sa.Column('squadron_id', sa.String(length=36), nullable=True),
    sa.Column('proxy_session_id', sa.String(length=36), nullable=True),
    sa.Column('object_type', sa.String(length=40), nullable=True),
    sa.Column('object_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_object_id'), 'audit_logs', ['object_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_object_type'), 'audit_logs', ['object_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_squadron_id'), 'audit_logs', ['squadron_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_wing_id'), 'audit_logs', ['wing_id'], unique=False)
    op.create_table('curriculum_items',
    sa.Column('owning_level', sa.String(length=20), nullable=False),
    sa.Column('wing_id', sa.String(length=36), nullable=True),
    sa.Column('squadron_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('phase', sa.String(length=40), nullable=False),
    sa.Column('element', sa.String(length=40), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('core_status', sa.String(length=20), nullable=False),
    sa.Column('learning_hub_url', sa.String(length=400), nullable=True),
    sa.Column('recommended_term', sa.String(length=10), nullable=True),
    sa.Column('recommended_sequence', sa.Integer(), nullable=False),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.Column('replacement_curriculum_id', sa.String(length=36), nullable=True),
    sa.Column('internal_admin_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_items_code'), 'curriculum_items', ['code'], unique=False)
    op.create_index(op.f('ix_curriculum_items_is_archived'), 'curriculum_items', ['is_archived'], unique=False)
    op.create_index(op.f('ix_curriculum_items_phase'), 'curriculum_items', ['phase'], unique=False)
    op.create_index(op.f('ix_curriculum_items_squadron_id'), 'curriculum_items', ['squadron_id'], unique=False)
    op.create_index(op.f('ix_curriculum_items_wing_id'), 'curriculum_items', ['wing_id'], unique=False)
    op.create_table('exceptions',
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('squadron_id', sa.String(length=36), nullable=True),
    sa.Column('wing_id', sa.String(length=36), nullable=True),
    sa.Column('source_module', sa.String(length=40), nullable=True),
    sa.Column('affected_object_type', sa.String(length=40), nullable=True),
    sa.Column('affected_object_id', sa.String(length=36), nullable=True),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('due_date', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exceptions_squadron_id'), 'exceptions', ['squadron_id'], unique=False)
    op.create_index(op.f('ix_exceptions_status'), 'exceptions', ['status'], unique=False)
    op.create_index(op.f('ix_exceptions_wing_id'), 'exceptions', ['wing_id'], unique=False)
    op.create_table('export_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('export_type', sa.String(length=40), nullable=False),
    sa.Column('filters', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=200), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('squadron_id', sa.String(length=36), nullable=True),
    sa.Column('import_type', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=True),
    sa.Column('rows_read', sa.Integer(), nullable=False),
    sa.Column('rows_accepted', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('validation_errors', sa.Text(), nullable=True),
    sa.Column('committed', sa.Integer(), nullable=False),
    sa.Column('rollback_status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_status',
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('result_reference', sa.String(length=300), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_hub_resources',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=400), nullable=False),
    sa.Column('phase', sa.String(length=80), nullable=True),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('requires_login', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('national_entities',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_name', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phases',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('short_name', sa.String(length=40), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('parent_program', sa.String(length=80), nullable=True),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('is_extension', sa.Boolean(), nullable=False),
    sa.Column('learning_hub_url', sa.String(length=400), nullable=True),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_packages',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description_internal', sa.Text(), nullable=True),
    sa.Column('owning_scope', sa.String(length=20), nullable=False),
    sa.Column('national_id', sa.String(length=36), nullable=True),
    sa.Column('wing_id', sa.String(length=36), nullable=True),
    sa.Column('squadron_id', sa.String(length=36), nullable=True),
    sa.Column('program_year', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.String(length=10), nullable=True),
    sa.Column('effective_to', sa.String(length=10), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('published_by', sa.String(length=36), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_packages_is_archived'), 'program_packages', ['is_archived'], unique=False)
    op.create_index(op.f('ix_program_packages_owning_scope'), 'program_packages', ['owning_scope'], unique=False)
    op.create_index(op.f('ix_program_packages_squadron_id'), 'program_packages', ['squadron_id'], unique=False)
    op.create_index(op.f('ix_program_packages_status'), 'program_packages', ['status'], unique=False)
    op.create_index(op.f('ix_program_packages_wing_id'), 'program_packages', ['wing_id'], unique=False)
    op.create_table('promotion_requests',
    sa.Column('program_item_id', sa.String(length=36), nullable=False),
    sa.Column('from_scope', sa.String(length=20), nullable=False),
    sa.Column('to_scope', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_requests_program_item_id'), 'promotion_requests', ['program_item_id'], unique=False)
    op.create_table('source_conflicts',
    sa.Column('source_file_id', sa.String(length=36), nullable=True),
    sa.Column('conflict_type', sa.String(length=60), nullable=False),
    sa.Column('object_type', sa.String(length=40), nullable=True),
    sa.Column('object_key', sa.String(length=80), nullable=True),
    sa.Column('field_name', sa.String(length=60), nullable=True),
    sa.Column('value_a', sa.Text(), nullable=True),
    sa.Column('value_b', sa.Text(), nullable=True),
    sa.Column('source_a', sa.String(length=80), nullable=True),
    sa.Column('source_b', sa.String(length=80), nullable=True),
    sa.Column('resolution_status', sa.String(length=20), nullable=False),
    sa.Column('resolved_value', sa.Text(), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_conflicts_source_file_id'), 'source_conflicts', ['source_file_id'], unique=False)
    op.create_table('source_files',
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('source_category', sa.String(length=40), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('parsed_status', sa.String(length=20), nullable=False),
    sa.Column('parser_version', sa.String(length=20), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_items',
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('owning_scope', sa.String(length=20), nullable=False),
    sa.Column('national_id', sa.String(length=36), nullable=True),
    sa.Column('wing_id', sa.String(length=36), nullable=True),
    sa.Column('squadron_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('phase_id', sa.String(length=36), nullable=True),
    sa.Column('phase_name_at_time', sa.String(length=80), nullable=True),
    sa.Column('element', sa.String(length=40), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('foundation_or_extension', sa.String(length=20), nullable=False),
    sa.Column('core_status', sa.String(length=20), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('duration_variable', sa.Boolean(), nullable=False),
    sa.Column('suggested_parts', sa.Integer(), nullable=True),
    sa.Column('instructor_suitability', sa.String(length=120), nullable=True),
    sa.Column('location_type', sa.String(length=40), nullable=True),
    sa.Column('required_equipment', sa.Text(), nullable=True),
    sa.Column('prerequisite_item_ids', sa.Text(), nullable=True),
    sa.Column('learning_hub_resource_id', sa.String(length=36), nullable=True),
    sa.Column('source_file_id', sa.String(length=36), nullable=True),
    sa.Column('source_row_reference', sa.String(length=80), nullable=True),
    sa.Column('source_sheet_name', sa.String(length=80), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('replacement_item_id', sa.String(length=36), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['program_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_items_code'), 'program_items', ['code'], unique=False)
    op.create_index(op.f('ix_program_items_is_archived'), 'program_items', ['is_archived'], unique=False)
    op.create_index(op.f('ix_program_items_learning_hub_resource_id'), 'program_items', ['learning_hub_resource_id'], unique=False)
    op.create_index(op.f('ix_program_items_owning_scope'), 'program_items', ['owning_scope'], unique=False)
    op.create_index(op.f('ix_program_items_package_id'), 'program_items', ['package_id'], unique=False)
    op.create_index(op.f('ix_program_items_phase_id'), 'program_items', ['phase_id'], unique=False)
    op.create_index(op.f('ix_program_items_squadron_id'), 'program_items', ['squadron_id'], unique=False)
    op.create_index(op.f('ix_program_items_status'), 'program_items', ['status'], unique=False)
    op.create_index(op.f('ix_program_items_wing_id'), 'program_items', ['wing_id'], unique=False)
    op.create_table('wings',
    sa.Column('national_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_name', sa.String(length=40), nullable=False),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['national_id'], ['national_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wings_code'), 'wings', ['code'], unique=True)
    op.create_index(op.f('ix_wings_is_archived'), 'wings', ['is_archived'], unique=False)
    op.create_index(op.f('ix_wings_national_id'), 'wings', ['national_id'], unique=False)
    op.create_table('program_item_deployments',
    sa.Column('program_item_id', sa.String(length=36), nullable=False),
    sa.Column('available_to_scope', sa.String(length=20), nullable=False),
    sa.Column('national_id', sa.String(length=36), nullable=True),
    sa.Column('wing_id', sa.String(length=36), nullable=True),
    sa.Column('squadron_id', sa.String(length=36), nullable=True),
    sa.Column('inherited_from_scope', sa.String(length=20), nullable=True),
    sa.Column('inherited_from_package_id', sa.String(length=36), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('can_schedule', sa.Boolean(), nullable=False),
    sa.Column('can_copy', sa.Boolean(), nullable=False),
    sa.Column('can_request_change', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['program_item_id'], ['program_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_item_deployments_available_to_scope'), 'program_item_deployments', ['available_to_scope'], unique=False)
    op.create_index(op.f('ix_program_item_deployments_program_item_id'), 'program_item_deployments', ['program_item_id'], unique=False)
    op.create_index(op.f('ix_program_item_deployments_squadron_id'), 'program_item_deployments', ['squadron_id'], unique=False)
    op.create_index(op.f('ix_program_item_deployments_wing_id'), 'program_item_deployments', ['wing_id'], unique=False)
    op.create_table('squadrons',
    sa.Column('wing_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('unit_number', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('short_name', sa.String(length=40), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('default_parade_day', sa.String(length=20), nullable=True),
    sa.Column('default_start_time', sa.String(length=10), nullable=True),
    sa.Column('default_end_time', sa.String(length=10), nullable=True),
    sa.Column('default_session_count', sa.Integer(), nullable=False),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wing_id'], ['wings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_squadrons_code'), 'squadrons', ['code'], unique=True)
    op.create_index(op.f('ix_squadrons_is_archived'), 'squadrons', ['is_archived'], unique=False)
    op.create_index(op.f('ix_squadrons_wing_id'), 'squadrons', ['wing_id'], unique=False)
    op.create_table('cadets',
    sa.Column('squadron_id', sa.String(length=36), nullable=False),
    sa.Column('service_number', sa.String(length=40), nullable=True),
    sa.Column('rank', sa.String(length=40), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('phase', sa.String(length=40), nullable=True),
    sa.Column('flight', sa.String(length=40), nullable=True),
    sa.Column('attendance_percentage', sa.Float(), nullable=True),
    sa.Column('recent_attendance_trend', sa.String(length=20), nullable=True),
    sa.Column('last_attended', sa.String(length=10), nullable=True),
    sa.Column('sitrep_part_1_status', sa.String(length=20), nullable=True),
    sa.Column('sitrep_part_2_status', sa.String(length=20), nullable=True),
    sa.Column('promotion_interest', sa.String(length=20), nullable=True),
    sa.Column('extension_completion', sa.String(length=20), nullable=True),
    sa.Column('support_flag', sa.Boolean(), nullable=False),
    sa.Column('support_notes', sa.Text(), nullable=True),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['squadron_id'], ['squadrons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cadets_is_archived'), 'cadets', ['is_archived'], unique=False)
    op.create_index(op.f('ix_cadets_service_number'), 'cadets', ['service_number'], unique=False)
    op.create_index(op.f('ix_cadets_squadron_id'), 'cadets', ['squadron_id'], unique=False)
    op.create_table('custom_phases',
    sa.Column('squadron_id', sa.String(length=36), nullable=False),
    sa.Column('phase_key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('abbr', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['squadron_id'], ['squadrons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_phases_squadron_id'), 'custom_phases', ['squadron_id'], unique=False)
    op.create_table('equipment',
    sa.Column('squadron_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['squadron_id'], ['squadrons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_is_archived'), 'equipment', ['is_archived'], unique=False)
    op.create_index(op.f('ix_equipment_squadron_id'), 'equipment', ['squadron_id'], unique=False)
    op.create_table('facilitators',
    sa.Column('squadron_id', sa.String(length=36), nullable=False),
    sa.Column('wing_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('current_rank', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.Column('subject_areas', sa.Text(), nullable=True),
    sa.Column('max_sessions_per_night', sa.Integer(), nullable=False),
    sa.Column('max_sessions_per_month', sa.Integer(), nullable=False),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['squadron_id'], ['squadrons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilitators_is_archived'), 'facilitators', ['is_archived'], unique=False)
    op.create_index(op.f('ix_facilitators_squadron_id'), 'facilitators', ['squadron_id'], unique=False)
    op.create_index(op.f('ix_facilitators_wing_id'), 'facilitators', ['wing_id'], unique=False)
    op.create_table('parade_nights',
    sa.Column('squadron_id', sa.String(length=36), nullable=False),
    sa.Column('wing_id', sa.String(length=36), nullable=False),
    sa.Column('training_year', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('term', sa.String(length=10), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('parade_type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('published_status', sa.Boolean(), nullable=False),
    sa.Column('readiness_score', sa.Integer(), nullable=False),
    sa.Column('closeout_status', sa.String(length=20), nullable=False),
    sa.Column('published_by', sa.String(length=36), nullable=True),
    sa.Column('closed_by', sa.String(length=36), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['squadron_id'], ['squadrons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parade_nights_date'), 'parade_nights', ['date'], unique=False)
    op.create_index(op.f('ix_parade_nights_is_archived'), 'parade_nights', ['is_archived'], unique=False)
    op.create_index(op.f('ix_parade_nights_squadron_id'), 'parade_nights', ['squadron_id'], unique=False)
    op.create_index(op.f('ix_parade_nights_training_year'), 'parade_nights', ['training_year'], unique=False)
    op.create_index(op.f('ix_parade_nights_wing_id'), 'parade_nights', ['wing_id'], unique=False)
    op.create_table('training_areas',
    sa.Column('squadron_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('indoor_outdoor', sa.String(length=20), nullable=True),
    sa.Column('availability_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['squadron_id'], ['squadrons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_areas_is_archived'), 'training_areas', ['is_archived'], unique=False)
    op.create_index(op.f('ix_training_areas_squadron_id'), 'training_areas', ['squadron_id'], unique=False)
    op.create_table('users',
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('national_id', sa.String(length=36), nullable=True),
    sa.Column('wing_id', sa.String(length=36), nullable=True),
    sa.Column('squadron_id', sa.String(length=36), nullable=True),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['national_id'], ['national_entities.id'], ),
    sa.ForeignKeyConstraint(['squadron_id'], ['squadrons.id'], ),
    sa.ForeignKeyConstraint(['wing_id'], ['wings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_is_archived'), 'users', ['is_archived'], unique=False)
    op.create_index(op.f('ix_users_national_id'), 'users', ['national_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_squadron_id'), 'users', ['squadron_id'], unique=False)
    op.create_index(op.f('ix_users_wing_id'), 'users', ['wing_id'], unique=False)
    op.create_table('access_codes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_codes_code_hash'), 'access_codes', ['code_hash'], unique=False)
    op.create_index(op.f('ix_access_codes_user_id'), 'access_codes', ['user_id'], unique=False)
    op.create_table('facilitator_rank_history',
    sa.Column('facilitator_id', sa.String(length=36), nullable=False),
    sa.Column('rank', sa.String(length=40), nullable=True),
    sa.Column('effective_from', sa.String(length=10), nullable=True),
    sa.Column('effective_to', sa.String(length=10), nullable=True),
    sa.Column('changed_by', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['facilitator_id'], ['facilitators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilitator_rank_history_facilitator_id'), 'facilitator_rank_history', ['facilitator_id'], unique=False)
    op.create_table('proxy_sessions',
    sa.Column('actor_user_id', sa.String(length=36), nullable=False),
    sa.Column('actor_role', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=40), nullable=False),
    sa.Column('acting_wing_id', sa.String(length=36), nullable=True),
    sa.Column('acting_squadron_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxy_sessions_actor_user_id'), 'proxy_sessions', ['actor_user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('parade_night_id', sa.String(length=36), nullable=False),
    sa.Column('squadron_id', sa.String(length=36), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('session_title', sa.String(length=200), nullable=True),
    sa.Column('curriculum_item_id', sa.String(length=36), nullable=True),
    sa.Column('curriculum_code_at_time', sa.String(length=40), nullable=True),
    sa.Column('curriculum_title_at_time', sa.String(length=200), nullable=True),
    sa.Column('custom_title', sa.String(length=200), nullable=True),
    sa.Column('phase_at_time', sa.String(length=40), nullable=True),
    sa.Column('element_at_time', sa.String(length=40), nullable=True),
    sa.Column('facilitator_id', sa.String(length=36), nullable=True),
    sa.Column('facilitator_rank_at_time', sa.String(length=40), nullable=True),
    sa.Column('facilitator_display_name_at_time', sa.String(length=120), nullable=True),
    sa.Column('assistant_facilitator_id', sa.String(length=36), nullable=True),
    sa.Column('backup_facilitator_id', sa.String(length=36), nullable=True),
    sa.Column('training_area_id', sa.String(length=36), nullable=True),
    sa.Column('training_area_name_at_time', sa.String(length=120), nullable=True),
    sa.Column('equipment_required', sa.Text(), nullable=True),
    sa.Column('expected_attendance', sa.Integer(), nullable=True),
    sa.Column('actual_attendance', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('delivery_notes', sa.Text(), nullable=True),
    sa.Column('issue_notes', sa.Text(), nullable=True),
    sa.Column('not_delivered_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('rescheduled_to_date', sa.String(length=10), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('follow_up_due_date', sa.String(length=10), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('evidence_url', sa.String(length=400), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parade_night_id'], ['parade_nights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_curriculum_item_id'), 'sessions', ['curriculum_item_id'], unique=False)
    op.create_index(op.f('ix_sessions_facilitator_id'), 'sessions', ['facilitator_id'], unique=False)
    op.create_index(op.f('ix_sessions_is_archived'), 'sessions', ['is_archived'], unique=False)
    op.create_index(op.f('ix_sessions_parade_night_id'), 'sessions', ['parade_night_id'], unique=False)
    op.create_index(op.f('ix_sessions_squadron_id'), 'sessions', ['squadron_id'], unique=False)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_table('session_status_history',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=True),
    sa.Column('changed_by', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_status_history_session_id'), 'session_status_history', ['session_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_status_history_session_id'), table_name='session_status_history')
    op.drop_table('session_status_history')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_squadron_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_parade_night_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_is_archived'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_facilitator_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_curriculum_item_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_proxy_sessions_actor_user_id'), table_name='proxy_sessions')
    op.drop_table('proxy_sessions')
    op.drop_index(op.f('ix_facilitator_rank_history_facilitator_id'), table_name='facilitator_rank_history')
    op.drop_table('facilitator_rank_history')
    op.drop_index(op.f('ix_access_codes_user_id'), table_name='access_codes')
    op.drop_index(op.f('ix_access_codes_code_hash'), table_name='access_codes')
    op.drop_table('access_codes')
    op.drop_index(op.f('ix_users_wing_id'), table_name='users')
    op.drop_index(op.f('ix_users_squadron_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_national_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_archived'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_training_areas_squadron_id'), table_name='training_areas')
    op.drop_index(op.f('ix_training_areas_is_archived'), table_name='training_areas')
    op.drop_table('training_areas')
    op.drop_index(op.f('ix_parade_nights_wing_id'), table_name='parade_nights')
    op.drop_index(op.f('ix_parade_nights_training_year'), table_name='parade_nights')
    op.drop_index(op.f('ix_parade_nights_squadron_id'), table_name='parade_nights')
    op.drop_index(op.f('ix_parade_nights_is_archived'), table_name='parade_nights')
    op.drop_index(op.f('ix_parade_nights_date'), table_name='parade_nights')
    op.drop_table('parade_nights')
    op.drop_index(op.f('ix_facilitators_wing_id'), table_name='facilitators')
    op.drop_index(op.f('ix_facilitators_squadron_id'), table_name='facilitators')
    op.drop_index(op.f('ix_facilitators_is_archived'), table_name='facilitators')
    op.drop_table('facilitators')
    op.drop_index(op.f('ix_equipment_squadron_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_is_archived'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_custom_phases_squadron_id'), table_name='custom_phases')
    op.drop_table('custom_phases')
    op.drop_index(op.f('ix_cadets_squadron_id'), table_name='cadets')
    op.drop_index(op.f('ix_cadets_service_number'), table_name='cadets')
    op.drop_index(op.f('ix_cadets_is_archived'), table_name='cadets')
    op.drop_table('cadets')
    op.drop_index(op.f('ix_squadrons_wing_id'), table_name='squadrons')
    op.drop_index(op.f('ix_squadrons_is_archived'), table_name='squadrons')
    op.drop_index(op.f('ix_squadrons_code'), table_name='squadrons')
    op.drop_table('squadrons')
    op.drop_index(op.f('ix_program_item_deployments_wing_id'), table_name='program_item_deployments')
    op.drop_index(op.f('ix_program_item_deployments_squadron_id'), table_name='program_item_deployments')
    op.drop_index(op.f('ix_program_item_deployments_program_item_id'), table_name='program_item_deployments')
    op.drop_index(op.f('ix_program_item_deployments_available_to_scope'), table_name='program_item_deployments')
    op.drop_table('program_item_deployments')
    op.drop_index(op.f('ix_wings_national_id'), table_name='wings')
    op.drop_index(op.f('ix_wings_is_archived'), table_name='wings')
    op.drop_index(op.f('ix_wings_code'), table_name='wings')
    op.drop_table('wings')
    op.drop_index(op.f('ix_program_items_wing_id'), table_name='program_items')
    op.drop_index(op.f('ix_program_items_status'), table_name='program_items')
    op.drop_index(op.f('ix_program_items_squadron_id'), table_name='program_items')
    op.drop_index(op.f('ix_program_items_phase_id'), table_name='program_items')
    op.drop_index(op.f('ix_program_items_package_id'), table_name='program_items')
    op.drop_index(op.f('ix_program_items_owning_scope'), table_name='program_items')
    op.drop_index(op.f('ix_program_items_learning_hub_resource_id'), table_name='program_items')
    op.drop_index(op.f('ix_program_items_is_archived'), table_name='program_items')
    op.drop_index(op.f('ix_program_items_code'), table_name='program_items')
    op.drop_table('program_items')
    op.drop_table('source_files')
    op.drop_index(op.f('ix_source_conflicts_source_file_id'), table_name='source_conflicts')
    op.drop_table('source_conflicts')
    op.drop_index(op.f('ix_promotion_requests_program_item_id'), table_name='promotion_requests')
    op.drop_table('promotion_requests')
    op.drop_index(op.f('ix_program_packages_wing_id'), table_name='program_packages')
    op.drop_index(op.f('ix_program_packages_status'), table_name='program_packages')
    op.drop_index(op.f('ix_program_packages_squadron_id'), table_name='program_packages')
    op.drop_index(op.f('ix_program_packages_owning_scope'), table_name='program_packages')
    op.drop_index(op.f('ix_program_packages_is_archived'), table_name='program_packages')
    op.drop_table('program_packages')
    op.drop_table('phases')
    op.drop_table('national_entities')
    op.drop_table('learning_hub_resources')
    op.drop_table('job_status')
    op.drop_table('import_logs')
    op.drop_table('export_logs')
    op.drop_index(op.f('ix_exceptions_wing_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_status'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_squadron_id'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_curriculum_items_wing_id'), table_name='curriculum_items')
    op.drop_index(op.f('ix_curriculum_items_squadron_id'), table_name='curriculum_items')
    op.drop_index(op.f('ix_curriculum_items_phase'), table_name='curriculum_items')
    op.drop_index(op.f('ix_curriculum_items_is_archived'), table_name='curriculum_items')
    op.drop_index(op.f('ix_curriculum_items_code'), table_name='curriculum_items')
    op.drop_table('curriculum_items')
    op.drop_index(op.f('ix_audit_logs_wing_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_squadron_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_object_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_object_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_activities_wing_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_squadron_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_is_archived'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_action_items_wing_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_status'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_squadron_id'), table_name='action_items')
    op.drop_table('action_items')
    # ### end Alembic commands ###
