"""v38_ip_api_requests_table
Revision ID: 3adfd5f63190
Revises: d3e4f5a6b7c8
Create Date: 2026-08-13 09:42:13.175404
"""
from alembic import op
import sqlalchemy as sa

revision = '3adfd5f63190'
down_revision = 'd3e4f5a6b7c8'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_api_requests',
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ip')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ip_api_requests')
    # ### end Alembic commands ###
