"""v52_parade_night_templates
Revision ID: c3cb76ef2cf7
Revises: 5cf6d7e8f9a0
Create Date: 2026-08-14 12:08:50.978864
"""
from alembic import op
import sqlalchemy as sa

revision = 'c3cb76ef2cf7'
down_revision = '5cf6d7e8f9a0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parade_night_templates',
    sa.Column('squadron_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['squadron_id'], ['squadrons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parade_night_templates_is_archived'), 'parade_night_templates', ['is_archived'], unique=False)
    op.create_index(op.f('ix_parade_night_templates_squadron_id'), 'parade_night_templates', ['squadron_id'], unique=False)
    op.create_table('parade_night_template_sessions',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('curriculum_item_id', sa.String(length=36), nullable=True),
    sa.Column('custom_title', sa.String(length=200), nullable=True),
    sa.Column('facilitator_id', sa.String(length=36), nullable=True),
    sa.Column('training_area_id', sa.String(length=36), nullable=True),
    sa.Column('cadet_group', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_item_id'], ['curriculum_items.id'], ),
    sa.ForeignKeyConstraint(['facilitator_id'], ['facilitators.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['parade_night_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_area_id'], ['training_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parade_night_template_sessions_template_id'), 'parade_night_template_sessions', ['template_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parade_night_template_sessions_template_id'), table_name='parade_night_template_sessions')
    op.drop_table('parade_night_template_sessions')
    op.drop_index(op.f('ix_parade_night_templates_squadron_id'), table_name='parade_night_templates')
    op.drop_index(op.f('ix_parade_night_templates_is_archived'), table_name='parade_night_templates')
    op.drop_table('parade_night_templates')
    # ### end Alembic commands ###
